version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "${NGINX_EXTERNAL_HTTP}:80"
    volumes:
      - ./src/:/var/www/html/
      - ./subdomain.bcom-helper.invalid.conf:/home/default.conf
    links:
      - vanilla_php
    # Leyendo las variables de entorno (envsubst) sustituir los matches con la config de nginx
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /home/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'; chown -R www-data:www-data /var/www/html/"
    #     .env - cargado antes   de interpretar este fichero, visibilidad solo fuera  del contenedor
    # XXXX.env - cargado después de interpretar este fichero, visibilidad solo dentro del contenedor
    env_file:
      - .env
  vanilla_php:
    image: php:7.3.1-fpm-alpine
    volumes:
      - ./src/:/var/www/html/
