version: '3'
services:
  node_project:
    image: node:alpine
    ports:
      - "8080:9898"
    volumes:
      - ./src/:/deploy/
      #- ./bcom-tools.service:/etc/systemd/system/bcom-tools.service
    #command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/systemd/system/bcom-tools.service > /etc/systemd/system/bcom-tools.service;systemctl daemon-reload;systemctl enable bcom-tools;systemctl start bcom-tools;"
    command: node /deploy/app.js
    env_file:
      - .env
